<?php

return array(
	'key' => 'group_accordions',
	'title' => 'Accordions',
	'fields' => array(
		array(
			'key' => 'field_5bbf864f973d5',
			'label' => 'Accordion Items',
			'name' => 'accordion_items',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Item',
			'sub_fields' => array(
				array(
					'key' => 'field_5bbf866d973d6',
					'label' => 'Title',
					'name' => 'accordion_item_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bbf8676973d7',
					'label' => 'Content',
					'name' => 'accordion_item_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'settings_tab' => array(
		array(
			'key' => 'field_32542i3wroen',
			'label' => 'Use Accordion as FAQ Schema',
			'name' => 'accordion_use_as_schema',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'true' => 'True',
				'false' => 'False',
			),
			'default_value' => 'false',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
);
