<?php

declare(strict_types=1);

namespace App\Setup;

class Options
{
	/**
	 * Initialization
	 * This method should be run from functions.php
	 * @return void
	 */
	public static function init(): void
	{
		add_action('acf/init', [__CLASS__, 'add_options_page']);
		add_action('acf/init', [__CLASS__, 'theme_options_page_fields']);
	}

	/**
	 * Requires ACF Theme Options Page Fields
	 * @return void
	 */
	public static function theme_options_page_fields(): void
	{

		if (function_exists('acf_add_local_field_group')) :
			acf_add_local_field_group(array(
				'key' => 'group_5ba1c04eb6142',
				'title' => 'Theme Options',
				'fields' => array(
					array(
						'key' => 'field_5p39hdk12343',
						'label' => 'Styling',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5b4_generic_label',
						'label' => '<h3 class="mb-0 mt-6">Generic</h3>',
						'name' => 'generic_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_component_padding_top',
						'label' => 'Component padding top',
						'name' => 'component_padding_top',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 100,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_component_padding_bottom',
						'label' => 'Component padding bottom',
						'name' => 'component_padding_bottom',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 100,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45tyrhgffs_label',
						'label' => '<h3 class="mb-0 mt-6">Fonts</h3>',
						'name' => 'fonts_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45tyrhgffs',
						'label' => 'Google Fonts URL',
						'name' => 'google_fonts_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45t4532452',
						'label' => 'Adobe Fonts URL',
						'name' => 'adobe_fonts_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45font1',
						'label' => 'Primary Font',
						'name' => 'font_primary',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45font2',
						'label' => 'Secondary Font',
						'name' => 'font_secondary',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45font3',
						'label' => 'Tertiary Font',
						'name' => 'font_tertiary',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45fontsizebase',
						'label' => 'Base Font Size',
						'name' => 'font_size_base',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontweightbase',
						'label' => 'Base font weight',
						'name' => 'font_weight_base',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45margintopbase',
						'label' => 'Base margin top',
						'name' => 'margin_top_base',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45marginbottombase',
						'label' => 'Base margin bottom',
						'name' => 'margin_bottom_base',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45fontsizesmall',
						'label' => 'Small Font Size',
						'name' => 'font_size_small',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontsizelarge',
						'label' => 'Large Font Size',
						'name' => 'font_size_large',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontsize1',
						'label' => 'H1 font size',
						'name' => 'font_size_h1',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontsizemobile1',
						'label' => 'H1 font size MOBILE',
						'name' => 'mobile_font_size_h1',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontweight1',
						'label' => 'H1 font weight',
						'name' => 'font_weight_h1',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45margintop1',
						'label' => 'H1 margin top',
						'name' => 'margin_top_h1',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45marginbottom1',
						'label' => 'H1 margin bottom',
						'name' => 'margin_bottom_h1',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45fontsize2',
						'label' => 'H2 font size',
						'name' => 'font_size_h2',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontsizemobile2',
						'label' => 'H2 font size MOBILE',
						'name' => 'mobile_font_size_h2',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontweight2',
						'label' => 'H2 font weight',
						'name' => 'font_weight_h2',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45margintop2',
						'label' => 'H2 margin top',
						'name' => 'margin_top_h2',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45marginbottom2',
						'label' => 'H2 margin bottom',
						'name' => 'margin_bottom_h2',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45fontsize3',
						'label' => 'H3 font size',
						'name' => 'font_size_h3',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontsizemobile3',
						'label' => 'H3 font size MOBILE',
						'name' => 'mobile_font_size_h3',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontweight3',
						'label' => 'H3 font weight',
						'name' => 'font_weight_h3',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45margintop3',
						'label' => 'H3 margin top',
						'name' => 'margin_top_h3',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45marginbottom3',
						'label' => 'H3 margin bottom',
						'name' => 'margin_bottom_h3',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45fontsize4',
						'label' => 'H4 font size',
						'name' => 'font_size_h4',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontsizemobile4',
						'label' => 'H4 font size MOBILE',
						'name' => 'mobile_font_size_h4',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontweight4',
						'label' => 'H4 font weight',
						'name' => 'font_weight_h4',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45margintop4',
						'label' => 'H4 margin top',
						'name' => 'margin_top_h4',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0.5,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45marginbottom4',
						'label' => 'H4 margin bottom',
						'name' => 'margin_bottom_h4',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45fontsize5',
						'label' => 'H5 font size',
						'name' => 'font_size_h5',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontsizemobile5',
						'label' => 'H5 font size MOBILE',
						'name' => 'mobile_font_size_h5',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontweight5',
						'label' => 'H5 font weight',
						'name' => 'font_weight_h5',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45margintop5',
						'label' => 'H5 margin top',
						'name' => 'margin_top_h5',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0.5,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45marginbottom5',
						'label' => 'H5 margin bottom',
						'name' => 'margin_bottom_h5',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45fontsize6',
						'label' => 'H6 font size',
						'name' => 'font_size_h6',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontsizemobile6',
						'label' => 'H6 font size MOBILE',
						'name' => 'mobile_font_size_h6',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b45fontweight6',
						'label' => 'H6 font weight',
						'name' => 'font_weight_h6',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b45margintop6',
						'label' => 'H6 margin top',
						'name' => 'margin_top_h6',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0.25,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b45marginbottom6',
						'label' => 'H6 margin bottom',
						'name' => 'margin_bottom_h6',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0.5,
						'placeholder' => '',
						'append' => 'EM'
					),
					array(
						'key' => 'field_5b4color_label',
						'label' => '<h3 class="mb-0 mt-6">Colors</h3>',
						'name' => 'colors_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color1',
						'label' => 'Primary color',
						'name' => 'color_primary',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color2',
						'label' => 'Secondary color',
						'name' => 'color_secondary',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color3',
						'label' => 'Tertiary color',
						'name' => 'color_tertiary',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color4',
						'label' => 'Color Light',
						'name' => 'color_light',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color5',
						'label' => 'Color Dark',
						'name' => 'color_dark',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color6',
						'label' => 'Color Success',
						'name' => 'color_success',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color7',
						'label' => 'Color Info',
						'name' => 'color_info',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color8',
						'label' => 'Color Warning',
						'name' => 'color_warning',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color9',
						'label' => 'Color Danger',
						'name' => 'color_danger',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4color10',
						'label' => 'Color Link',
						'name' => 'color_link',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4logo_label',
						'label' => '<h3 class="mb-0 mt-6">Logo</h3>',
						'name' => 'logo_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4logoheader',
						'label' => 'Logo Header',
						'name' => 'logo_header',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'return_format' => 'array',
					),
					array(
						'key' => 'field_5b4logoheaderwidth',
						'label' => 'Logo Header width',
						'name' => 'logo_header_width',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px',
					),
					array(
						'key' => 'field_5b4logofooter',
						'label' => 'Logo Footer',
						'name' => 'logo_footer',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'return_format' => 'array',
					),
					array(
						'key' => 'field_5b4logofooterwidth',
						'label' => 'Logo Footer width',
						'name' => 'logo_footer_width',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px',
					),
					array(
						'key' => 'field_5b4radius_label',
						'label' => '<h3 class="mb-0 mt-6">Border radius</h3>',
						'name' => 'radius_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4border_radius_sm',
						'label' => 'Border radius small',
						'name' => 'border_radius_sm',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33',
							'class' => '',
							'id' => '',
						),
						'default_value' => 5,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4border_radius_md',
						'label' => 'Border radius medium',
						'name' => 'border_radius_md',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33',
							'class' => '',
							'id' => '',
						),
						'default_value' => 8,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4border_radius_lg',
						'label' => 'Border radius large',
						'name' => 'border_radius_lg',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33',
							'class' => '',
							'id' => '',
						),
						'default_value' => 16,
						'placeholder' => '',
						'append' => 'px'
					),

					array(
						'key' => 'field_5b4_button_label',
						'label' => '<h3 class="mb-0 mt-6">Buttons design</h3>',
						'name' => 'button_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_icon',
						'label' => 'Button Icon',
						'name' => 'button_icon',
						'type' => 'text',
						'instructions' => 'Find the icon on <a href="https://fontawesome.com/search" target="_blank">FontAwesome</a> website and copy it’s code here.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_icon_choosed',
						'label' => 'Which button should have icon',
						'name' => 'button_icon_choosed',
						'type' => 'checkbox',
						'instructions' => 'Find the icon on <a href="https://fontawesome.com/search" target="_blank">FontAwesome</a> website and copy it’s code here.',
						'required' => 0,
						'conditional_logic' => array(
							array(
								'field' => 'field_5b4_button_icon',
								'operator' => '!=empty',
							)
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							"btn-primary" => "Primary",
							"btn-secondary" => "Secondary",
							"btn-tertiary" => "Tertiary",
							"btn-text" => "Text",
							"btn-link" => "Link",
							"btn-outline-primary" => "Outline Primary",
							"btn-outline-secondary" => "Outline Secondary",
							"btn-outline-tertiary" => "Outline Tertiary",
						),
						'default_value' => '',
						'placeholder' => '',
						'ui' => 1,
					),
					array(
						'key' => 'field_5b4_button_label_sm',
						'label' => '<h5 class="mb-0 mt-4">Button small</h5>',
						'name' => 'button_label_sm',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_padding_y_sm',
						'label' => 'Padding Vertical',
						'name' => 'button_padding_y_sm',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 5,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_padding_x_sm',
						'label' => 'Padding Horizontal',
						'name' => 'button_padding_x_sm',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 10,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_font_sm',
						'label' => 'Font Size',
						'name' => 'button_font_sm',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'default_value' => 14,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_weight_sm',
						'label' => 'Font Weight',
						'name' => 'button_weight_sm',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_radius_sm',
						'label' => 'Border radius',
						'name' => 'button_radius_sm',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none'   => 'None',
							'radius_sm'   => 'Small',
							'radius_md'   => 'Medium',
							'radius_lg'   => 'Large',
						),
						'default_value' => 'none',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_label_md',
						'label' => '<h5 class="mb-0 mt-4">Button medium</h5>',
						'name' => 'button_label_md',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_padding_y_md',
						'label' => 'Padding Vertical',
						'name' => 'button_padding_y_md',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 8,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_padding_x_md',
						'label' => 'Padding Horizontal',
						'name' => 'button_padding_x_md',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 16,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_font_md',
						'label' => 'Font Size',
						'name' => 'button_font_md',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'default_value' => 16,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_weight_md',
						'label' => 'Font Weight',
						'name' => 'button_weight_md',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_radius_md',
						'label' => 'Border radius',
						'name' => 'button_radius_md',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none'   => 'None',
							'radius_sm'   => 'Small',
							'radius_md'   => 'Medium',
							'radius_lg'   => 'Large',
						),
						'default_value' => 'none',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_label_lg',
						'label' => '<h5 class="mb-0 mt-4">Button large</h5>',
						'name' => 'button_label_lg',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_padding_y_lg',
						'label' => 'Padding Vertical',
						'name' => 'button_padding_y_lg',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 12,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_padding_x_lg',
						'label' => 'Padding Horizontal',
						'name' => 'button_padding_x_lg',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 30,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_font_lg',
						'label' => 'Font Size',
						'name' => 'button_font_lg',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'default_value' => 20,
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_button_weight_lg',
						'label' => 'Font Weight',
						'name' => 'button_weight_lg',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							100   => '100',
							200   => '200',
							300   => '300',
							400   => '400',
							500   => '500',
							600   => '600',
							700   => '700',
							800   => '800',
							900   => '900',
						),
						'default_value' => 400,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_button_radius_lg',
						'label' => 'Border radius',
						'name' => 'button_radius_lg',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none'   => 'None',
							'radius_sm'   => 'Small',
							'radius_md'   => 'Medium',
							'radius_lg'   => 'Large',
						),
						'default_value' => 'none',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4cards_label',
						'label' => '<h3 class="mb-0 mt-6">Cards design</h3>',
						'name' => 'cards_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_cards_padding_y',
						'label' => 'Padding Vertical',
						'name' => 'cards_padding_y',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_cards_padding_x',
						'label' => 'Padding Horizontal',
						'name' => 'cards_padding_x',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_cards_gutter',
						'label' => 'Grid Gutter',
						'name' => 'cards_gutter',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_cards_radius',
						'label' => 'Border radius',
						'name' => 'cards_radius',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none'   => 'None',
							'radius_sm'   => 'Small',
							'radius_md'   => 'Medium',
							'radius_lg'   => 'Large',
						),
						'default_value' => 'none',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_cards_col_xs',
						'label' => 'Columns XS',
						'name' => 'cards_cols_xs',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '16.6666',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1   => '1',
							2   => '2',
							3	=> '3',
							4	=> '4',
							6 	=> '6',
							12 	=> '12',
						),
						'default_value' => 1,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_cards_col_sm',
						'label' => 'Columns SM',
						'name' => 'cards_cols_sm',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '16.6666',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1   => '1',
							2   => '2',
							3	=> '3',
							4	=> '4',
							6 	=> '6',
							12 	=> '12',
						),
						'default_value' => 1,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_cards_col_md',
						'label' => 'Columns MD',
						'name' => 'cards_cols_md',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '16.6666',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1   => '1',
							2   => '2',
							3	=> '3',
							4	=> '4',
							6 	=> '6',
							12 	=> '12',
						),
						'default_value' => 2,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_cards_col_lg',
						'label' => 'Columns LG',
						'name' => 'cards_cols_lg',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '16.6666',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1   => '1',
							2   => '2',
							3	=> '3',
							4	=> '4',
							6 	=> '6',
							12 	=> '12',
						),
						'default_value' => 2,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_cards_col_xl',
						'label' => 'Columns XL',
						'name' => 'cards_cols_xl',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '16.6666',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1   => '1',
							2   => '2',
							3	=> '3',
							4	=> '4',
							6 	=> '6',
							12 	=> '12',
						),
						'default_value' => 3,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_cards_col_xxl',
						'label' => 'Columns XXL',
						'name' => 'cards_cols_xxl',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '16.6666',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1   => '1',
							2   => '2',
							3	=> '3',
							4	=> '4',
							6 	=> '6',
							12 	=> '12',
						),
						'default_value' => 3,
						'placeholder' => '',
					),
					/**
					 * End of CARDS DESIGN
					 */
					array(
						'key' => 'field_5b4_accordion_label',
						'label' => '<h3 class="mb-0 mt-6">Accordion design</h3>',
						'name' => 'accordion_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_accordion_label',
						'label' => '<h3 class="mb-0 mt-6">Accordion design</h3>',
						'name' => 'accordion_label',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_accordion_padding_y',
						'label' => 'Padding Vertical',
						'name' => 'accordion_padding_y',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_accordion_padding_x',
						'label' => 'Padding Horizontal',
						'name' => 'accordion_padding_x',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'append' => 'px'
					),
					array(
						'key' => 'field_5b4_accordion_radius',
						'label' => 'Border radius',
						'name' => 'accordion_radius',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none'   => 'None',
							'radius_sm'   => 'Small',
							'radius_md'   => 'Medium',
							'radius_lg'   => 'Large',
						),
						'default_value' => 'none',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_accordion_border_b',
						'label' => 'Border bottom width',
						'name' => 'accordion_border_b',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b4_accordion_gap',
						'label' => 'Items gap',
						'name' => 'accordion_gap',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 20,
						'placeholder' => '',
					),
					// array(
					// 	'key' => 'field_5b4_accordion_bg_color',
					// 	'label' => 'Accordion BG Color',
					// 	'name' => 'accordion_bg_color',
					// 	'type' => 'color_picker',
					// 	'instructions' => '',
					// 	'required' => 0,
					// 	'conditional_logic' => 0,
					// 	'wrapper' => array(
					// 		'width' => '',
					// 		'class' => '',
					// 		'id' => '',
					// 	),
					// 	'capability' => '',
					// 	'default_value' => '',
					// 	'enable_opacity' => 1,
					// 	'return_format' => 'array',
					// 	'allow_in_bindings' => 0,
					// ),
					/**
					 * End of STYLING
					 */
					array(
						'key' => 'field_5p39hdkdncwp3zzz',
						'label' => 'Header',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_656sdfsdf3333',
						'label' => 'Header CTA Text',
						'name' => 'global_header_cta_text',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'capability' => '',
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_b8kgragwrdbf8c5',
						'label' => 'CV Upload Form EN',
						'name' => 'cv_upload_form_en',
						'type' => 'forms',
						'instructions' => 'Choose CV Upload Form',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'post_object',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array(
						'key' => 'field_b8kgrasdfw2ef32g4v8c5',
						'label' => 'CV Upload Form NL',
						'name' => 'cv_upload_form_nl',
						'type' => 'forms',
						'instructions' => 'Choose CV Upload Form',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'post_object',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array(
						'key' => 'field_b8kgrasdfq4htrsh232g4v8c5',
						'label' => 'Job Application Form EN',
						'name' => 'job_apply_form_en',
						'type' => 'forms',
						'instructions' => 'Choose Job Application Form',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'post_object',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array(
						'key' => 'field_b8kgrasdfqrthh535',
						'label' => 'Job Application Form NL',
						'name' => 'job_apply_form_nl',
						'type' => 'forms',
						'instructions' => 'Choose Job Application Form',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'post_object',
						'allow_null' => 0,
						'multiple' => 0,
					),
					/**
					 * End of HEADER
					 */
					array(
						'key' => 'field_5p39hdkdncwp3',
						'label' => 'Tracking/Analytics',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1c7757bafd',
						'label' => 'Google Analytics',
						'name' => 'google_analytics',
						'type' => 'text',
						'instructions' => 'Enter the GTM Tracking Code without the GTM- prefix.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'prepend' => 'GTM-',
					),
					array(
						'key' => 'field_5ba26139f7892',
						'label' => 'API Keys',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1c968ed507',
						'label' => 'Google Maps API Key',
						'name' => 'google_maps_api_key',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba1c86344d49',
						'label' => 'Social Media',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1c7ffc2ba7',
						'label' => 'Facebook Link',
						'name' => 'facebook_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1c813c2ba8',
						'label' => 'Twitter Link',
						'name' => 'twitter_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1c81dc2ba9',
						'label' => 'Instagram Link',
						'name' => 'instagram_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1c825c2baa',
						'label' => 'Youtube Link',
						'name' => 'youtube_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5mm3a4v4m88mx',
						'label' => 'Pinterest Link',
						'name' => 'pinterest_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1cajs84ns0',
						'label' => 'Linkedin',
						'name' => 'linkedin_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5skdjfh385e62',
						'label' => 'Flickr',
						'name' => 'flickr_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5skdjfh385e62',
						'label' => 'TikTok',
						'name' => 'tiktok_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					/**
					 * End of ANALYTICS
					 */
					array(
						'key' => 'field_5ba1cb22eba88',
						'label' => 'Contact Info',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1cb45eba89',
						'label' => 'Address',
						'name' => 'address',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_5ba1cb4sdf5eba89',
						'label' => 'Address 2',
						'name' => 'address_2',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_5ba1csdfbrvb45eba89',
						'label' => 'Address 3',
						'name' => 'address_3',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_5ba1cb74eba8a',
						'label' => 'Phone Number',
						'name' => 'phone_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '(555) 555-5555',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba26166f7895',
						'label' => 'Email',
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5ba1987df330',
						'label' => 'Google Map Embed Code',
						'name' => 'google_map_embed_code',
						'type' => 'textarea',
						'instructions' => 'No API Key Required',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '<iframe src="https://www.google.com/maps/embed?xxx"></iframe>',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
					),
					array(
						'key' => 'field_5bdc7d1763165',
						'label' => 'Google Map',
						'name' => 'google_map',
						'type' => 'google_map',
						'instructions' => 'API Key Required',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'center_lat' => '',
						'center_lng' => '',
						'zoom' => '',
						'height' => '',
					),
					array(
						'key' => 'field_5bd77877c8550',
						'label' => 'Login Page',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5bd78770fcf3c',
						'label' => 'Login Logo',
						'name' => 'login_logo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
					),
					array(
						'key' => 'field_5bd7788ac8551',
						'label' => 'Login BG Type',
						'name' => 'login_bg_type',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'color' => 'Color',
							'image' => 'Image',
						),
						'allow_null' => 1,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5bd778cfc8552',
						'label' => 'Login BG Color',
						'name' => 'login_bg_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5bd7788ac8551',
									'operator' => '==',
									'value' => 'color',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
					array(
						'key' => 'field_5bd778f0c8553',
						'label' => 'Login BG Image',
						'name' => 'login_bg_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5bd7788ac8551',
									'operator' => '==',
									'value' => 'image',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
					),
					array(
						'key' => 'field_53xn4839049n2',
						'label' => 'Custom Scripts',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1c8d8ed505',
						'label' => 'Head Tag Scripts',
						'name' => 'global_head_scripts',
						'type' => 'textarea',
						'instructions' => 'Enter Scripts to be loaded in the head tag.<br>Scripts registered in the head are render-blocking and will affect page load speed.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_43tyeshdfgswe45',
						'label' => 'Body Open Scripts',
						'name' => 'global_body_open_scripts',
						'type' => 'textarea',
						'instructions' => 'Enter Scripts to be loaded immediately after the body tag.<br>Scripts registered in the body are render-blocking and will affect page load speed.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 11,
						'new_lines' => '',
					),
					array(
						'key' => 'field_5ba1c8f7ed506',
						'label' => 'Footer Scripts',
						'name' => 'global_footer_scripts',
						'type' => 'textarea',
						'instructions' => 'Enter Scripts to be loaded in the footer.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_604a5346303a4',
						'label' => 'Blog Posts',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_43w6tgfzaswerw',
						'label' => 'Related Posts Heading',
						'name' => 'related_posts_heading',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array(
						'key' => 'field_24536yetrsezrs',
						'label' => 'Blog Default Image',
						'name' => 'blog_default_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'medium_large',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
					),
					array(
						'key' => 'field_2134t4f3rrvf2g4',
						'label' => 'Blog Component Picker',
						'name' => 'blog_component_picker',
						'type' => 'relationship',
						'instructions' => 'Manually select a collection of components from the available items.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'globalcomponent',
						),
						'taxonomy' => '',
						'filters' => array(
							0 => 'search',
						),
						'elements' => array(
							0 => 'title',
						),
						'return_format' => 'id',
					),
					array(
						'key' => 'field_2134tg453rer2g4',
						'label' => 'Post Component Picker',
						'name' => 'post_component_picker',
						'type' => 'relationship',
						'instructions' => 'Manually select a collection of components from the available items.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'globalcomponent',
						),
						'taxonomy' => '',
						'filters' => array(
							0 => 'search',
						),
						'elements' => array(
							0 => 'title',
						),
						'return_format' => 'id',
					),
					array(
						'key' => 'field_603e862060183',
						'label' => '404',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_603e84ee6017d',
						'label' => 'Heading',
						'name' => '404_header',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '4',
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_603e85e660181',
						'label' => 'Subheading',
						'name' => '404_subheading',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_603e81696017c',
						'label' => 'Background Image',
						'name' => '404_background_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium_large',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
					),
					array(
						'key' => 'field_603e870339650',
						'label' => 'Text Theme',
						'name' => '404_text_theme',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'dark' => 'Dark',
							'light' => 'Light',
						),
						'allow_null' => 0,
						'default_value' => 'dark',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_65rtg35erererv',
						'label' => 'Footer',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_65rtgf24vrfsrererv',
						'label' => 'Footer text',
						'name' => 'footer_text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array(
						'key' => 'field_65rtgf24vdsfsdfewsfererv',
						'label' => 'Footer gallery',
						'name' => 'footer_gallery',
						'type' => 'gallery',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
					)
				),
				'location' => array(
					array(
						array(
							'param' => 'options_page',
							'operator' => '==',
							'value' => 'theme-options',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

			acf_add_local_field_group(array(
				'key' => 'group_786utyfre4w5e62qt',
				'title' => 'Header Style',
				'fields' => array(
					array(
						'key' => 'field_6198319a517ab',
						'label' => 'Header Transparent',
						'name' => 'header_transparent',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'capability' => '',
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '!=',
							'value' => 'null',
						),
					),
				),
				'menu_order' => 40,
				'position' => 'side',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}

	/**
	 * ACF Options Page
	 */
	public static function add_options_page()
	{
		if (function_exists('acf_add_options_page')) {

			acf_add_options_page(array(
				'page_title'    => 'Theme Options',
				'menu_title'    => 'Theme Options',
				'menu_slug'     => 'theme-options',
				'icon_url'      => 'dashicons-admin-settings',
				'capability'    => 'update_core',
				'position'      => 2
			));
		}
	}
}
