<?php
return array(
	'key' => 'group_video_player',
	'title' => 'Video Player',
	'fields' => array(
		array(
			'key' => 'field_890h233q4awew',
			'label' => 'Video Source',
			'name' => 'source',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'video' => 'Media Library',
				'embed' => 'Embed',
			),
			'default_value' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_539483n4374nbb9',
			'label' => 'Poster',
			'name' => 'video_player_poster',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.jpg, .jpeg, .png, .mp4, .webm, .webp, .svg, .gif',
		),
		array(
			'key' => 'field_239487n30m34jd83',
			'label' => 'Video Source',
			'name' => 'video',
			'type' => 'file',
			'required' => 1,
			'return_format' => 'url',
			'library' => 'all',
			'mime_types' => '.mp4, .webm',
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_890h233q4awew',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
		),
		array(
			'key' => 'field_631f8cbbaa107',
			'label' => 'Embed',
			'name' => 'embed',
			'type' => 'text',
			'placeholder' => 'Enter URL',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_890h233q4awew',
						'operator' => '==',
						'value' => 'embed',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'capability' => '',
			'width' => '',
			'height' => '',
		),
		array(
			'key' => 'field_333r24t3y5htebfdq4ew',
			'label' => 'Autoplay',
			'name' => 'video_autoplay',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				true => 'Yes',
				false => 'No',
			),
			'default_value' => false,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
);
