<?php

declare(strict_types=1);

namespace App\Gutenberg;

/**
 * DefaultFields class.
 *
 * @category Builder
 */
abstract class DefaultFields
{
	/**
	 * @var array An array of Advanced Custom Field data.
	 *
	 * @since 0.7.0
	 */
	public $content_tab = [
		[
			"key" => "field_5bdb35a44e72e",
			"label" => "Content",
			"name" => "",
			"type" => "tab",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			"placement" => "top",
			"endpoint" => 0,
		],
		[
			"key" => "field_508scge52vn39",
			"label" => "Pre/Sub Header",
			"name" => "component_sub_header",
			"type" => "text",
			"instructions" =>
			"Title to show above the Primary Header (Optional). Defaults to Parent Page if set.",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
			"placeholder" => "",
			"prepend" => "",
			"append" => "",
			"maxlength" => "",
		],
		[
			"key" => "field_5cf71835a9438c2",
			"label" => "Pre/Sub Header Tag",
			"name" => "component_sub_header_tag",
			"type" => "button_group",
			"instructions" => "Choose a component Pre/Sub Header Tag",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_508scge52vn39",
						"operator" => "!=empty",
					],
				],
			],
			"wrapper" => [
				"width" => "30",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"p" => "P",
				"h1" => "H1",
				"h2" => "H2",
				"h3" => "H3",
				"h4" => "H4",
				"h5" => "H5",
				"h6" => "H6",
			],
			"allow_null" => 0,
			"default_value" => "p",
			"layout" => "horizontal",
			"return_format" => "value",
		],
		[
			"key" => "field_5c71s8f3b9438c3",
			"label" => "Pre/Sub Header Style",
			"name" => "component_sub_header_style",
			"type" => "select",
			"instructions" => "Choose a Pre/Sub Header Style (optional).",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_508scge52vn39",
						"operator" => "!=empty",
					],
				],
			],
			"wrapper" => [
				"width" => "30",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"h1" => "H1",
				"h2" => "H2",
				"h3" => "H3",
				"h4" => "H4",
				"h5" => "H5",
				"h6" => "H6",
				"lead" => "Lead",
				"preheader" => "Preheader"
			],
			"default_value" => "preheader",
			"allow_null" => 1,
			"multiple" => 0,
			"ui" => 0,
			"ajax" => 0,
			"return_format" => "value",
			"placeholder" => "",
		],
		[
			"key" => "field_5c7123456ytrfhgd",
			"label" => "Pre/Sub Header Class",
			"name" => "component_sub_header_class",
			"type" => "text",
			"instructions" => "Choose a Pre/Sub Header Class (optional).",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_508scge52vn39",
						"operator" => "!=empty",
					],
				],
			],
			"wrapper" => [
				"width" => "40",
				"class" => "",
				"id" => "",
			],
			"allow_null" => 1,
			"placeholder" => "",
		],
		[
			"key" => "field_5c646291133db",
			"label" => "Header",
			"name" => "component_header",
			"type" => "textarea",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
			"placeholder" => "",
			"maxlength" => "",
			"rows" => 3,
			"new_lines" => "br",
		],
		[
			"key" => "field_4356457uw5agw",
			"label" => "Screen Reader Header",
			"name" => "screen_reader_header",
			"type" => "button_group",
			"instructions" =>
			"Choose whether the header should only display for screen readers.",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_5c646291133db",
						"operator" => "!=empty",
					],
				],
			],
			"wrapper" => [
				"width" => "25",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"false" => "False",
				"true" => "True",
			],
			"allow_null" => 0,
			"default_value" => "false",
			"layout" => "horizontal",
			"return_format" => "value",
		],
		[
			"key" => "field_5c718359438c2",
			"label" => "Header Tag",
			"name" => "component_header_tag",
			"type" => "button_group",
			"instructions" => "Choose a component Header Tag",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_5c646291133db",
						"operator" => "!=empty",
					],
				],
			],
			"wrapper" => [
				"width" => "25",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"h1" => "H1",
				"h2" => "H2",
				"h3" => "H3",
				"h4" => "H4",
				"h5" => "H5",
				"h6" => "H6",
				"p" => "P",
			],
			"allow_null" => 0,
			"default_value" => "h2",
			"layout" => "horizontal",
			"return_format" => "value",
		],
		[
			"key" => "field_5c7183b9438c3",
			"label" => "Header Style",
			"name" => "component_header_style",
			"type" => "select",
			"instructions" => "Choose a Header Style (optional).",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_5c646291133db",
						"operator" => "!=empty",
					],
				],
			],
			"wrapper" => [
				"width" => "25",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"h1" => "H1",
				"h2" => "H2",
				"h3" => "H3",
				"h4" => "H4",
				"h5" => "H5",
				"h6" => "H6",
				"lead" => "Lead",
			],
			"default_value" => [
				0 => "default",
			],
			"allow_null" => 1,
			"multiple" => 0,
			"ui" => 0,
			"ajax" => 0,
			"return_format" => "value",
			"placeholder" => "",
		],
		[
			"key" => "field_5c712345345yrggtg",
			"label" => "Header Class",
			"name" => "component_header_class",
			"type" => "text",
			"instructions" => "Choose a Header Class (optional).",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_5c646291133db",
						"operator" => "!=empty",
					],
				],
			],
			"wrapper" => [
				"width" => "25",
				"class" => "",
				"id" => "",
			],
			"allow_null" => 1,
			"placeholder" => "",
		],
		[
			"key" => "field_598376dksck3u",
			"label" => "Text",
			"name" => "component_text",
			"type" => "wysiwyg",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
			"tabs" => "all",
			"toolbar" => "full",
			"media_upload" => 1,
			"delay" => 1,
		],
		[
			"key" => "field_5c7qwdpmvvvf3b9438c3",
			"label" => "Text font size",
			"name" => "component_text_font_size",
			"type" => "select",
			"instructions" => "Choose a Text Font Size (optional).",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_598376dksck3u",
						"operator" => "!=empty",
					],
				],
			],
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"h1" => "H1",
				"h2" => "H2",
				"h3" => "H3",
				"h4" => "H4",
				"h5" => "H5",
				"h6" => "H6",
				"lead" => "Large",
				"small" => "Small",
				"" => "Default"
			],
			"default_value" => "",
			"allow_null" => 1,
			"multiple" => 0,
			"ui" => 0,
			"ajax" => 0,
			"return_format" => "value",
			"placeholder" => "",
		],
		[
			"key" => "field_398472hn3e9123r3w",
			"label" => "Component Link",
			"name" => "component_link",
			"type" => "link",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"return_format" => "array",
		],
		[
			"key" => "field_235rtserth5yt4r",
			"label" => "Component Link Style",
			"name" => "component_link_style",
			"type" => "select",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_398472hn3e9123r3w",
						"value" => "!empty",
					],
				],
			],
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"btn btn-primary" => "Primary",
				"btn btn-secondary" => "Secondary",
				"btn btn-tertiary" => "Tertiary",
				"btn btn-danger" => "Danger",
				"btn btn-warning" => "Warning",
				"btn btn-success" => "Success",
				"btn btn-info" => "Info",
				"btn btn-light" => "Light",
				"btn btn-text" => "Text",
				"btn btn-link" => "Link",
				"btn btn-outline-primary" => "Outline Primary",
				"btn btn-outline-secondary" => "Outline Secondary",
				"btn btn-outline-tertiary" => "Outline Tertiary",
				"btn btn-outline-danger" => "Outline Danger",
				"btn btn-outline-warning" => "Outline Warning",
				"btn btn-outline-success" => "Outline Success",
				"btn btn-outline-info" => "Outline Info",
				"btn btn-outline-light" => "Outline Light",
			],
			"default_value" => "btn btn-primary",
			"allow_null" => 0,
			"multiple" => 0,
			"ui" => 0,
			"return_format" => "value",
			"ajax" => 0,
			"placeholder" => "",
		],
		[
			"key" => "field_398472hnfdb3e9123r3w",
			"label" => "Component Link 2",
			"name" => "component_link_2",
			"type" => "link",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"return_format" => "array",
		],
		[
			"key" => "field_235rtserth53wgryt4r",
			"label" => "Component Link Style 2",
			"name" => "component_link_style_2",
			"type" => "select",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_398472hnfdb3e9123r3w",
						"value" => "!empty",
					],
				],
			],
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"btn btn-primary" => "Primary",
				"btn btn-secondary" => "Secondary",
				"btn btn-tertiary" => "Tertiary",
				"btn btn-danger" => "Danger",
				"btn btn-warning" => "Warning",
				"btn btn-success" => "Success",
				"btn btn-info" => "Info",
				"btn btn-light" => "Light",
				"btn btn-text" => "Text",
				"btn btn-link" => "Link",
				"btn btn-outline-primary" => "Outline Primary",
				"btn btn-outline-secondary" => "Outline Secondary",
				"btn btn-outline-tertiary" => "Outline Tertiary",
				"btn btn-outline-danger" => "Outline Danger",
				"btn btn-outline-warning" => "Outline Warning",
				"btn btn-outline-success" => "Outline Success",
				"btn btn-outline-info" => "Outline Info",
				"btn btn-outline-light" => "Outline Light",
			],
			"default_value" => "btn btn-primary",
			"allow_null" => 0,
			"multiple" => 0,
			"ui" => 0,
			"return_format" => "value",
			"ajax" => 0,
			"placeholder" => "",
		],
		[
			"key" => "field_398472hnfdb3e9123r3w3",
			"label" => "Component Link 3",
			"name" => "component_link_3",
			"type" => "link",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"return_format" => "array",
		],
		[
			"key" => "field_235rtserth53wgryt4r3",
			"label" => "Component Link Style 3",
			"name" => "component_link_style_3",
			"type" => "select",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_398472hnfdb3e9123r3w3",
						"value" => "!empty",
					],
				],
			],
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"btn btn-primary" => "Primary",
				"btn btn-secondary" => "Secondary",
				"btn btn-tertiary" => "Tertiary",
				"btn btn-danger" => "Danger",
				"btn btn-warning" => "Warning",
				"btn btn-success" => "Success",
				"btn btn-info" => "Info",
				"btn btn-light" => "Light",
				"btn btn-text" => "Text",
				"btn btn-link" => "Link",
				"btn btn-outline-primary" => "Outline Primary",
				"btn btn-outline-secondary" => "Outline Secondary",
				"btn btn-outline-tertiary" => "Outline Tertiary",
				"btn btn-outline-danger" => "Outline Danger",
				"btn btn-outline-warning" => "Outline Warning",
				"btn btn-outline-success" => "Outline Success",
				"btn btn-outline-info" => "Outline Info",
				"btn btn-outline-light" => "Outline Light",
			],
			"default_value" => "btn btn-primary",
			"allow_null" => 0,
			"multiple" => 0,
			"ui" => 0,
			"return_format" => "value",
			"ajax" => 0,
			"placeholder" => "",
		],
		[
			"key" => "field_398472hnfdb3e9123r3w4",
			"label" => "Component Link 4",
			"name" => "component_link_4",
			"type" => "link",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"return_format" => "array",
		],
		[
			"key" => "field_235rtserth53wgryt4r4",
			"label" => "Component Link Style 4",
			"name" => "component_link_style_4",
			"type" => "select",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_398472hnfdb3e9123r3w4",
						"value" => "!empty",
					],
				],
			],
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"btn btn-primary" => "Primary",
				"btn btn-secondary" => "Secondary",
				"btn btn-tertiary" => "Tertiary",
				"btn btn-danger" => "Danger",
				"btn btn-warning" => "Warning",
				"btn btn-success" => "Success",
				"btn btn-info" => "Info",
				"btn btn-light" => "Light",
				"btn btn-text" => "Text",
				"btn btn-link" => "Link",
				"btn btn-outline-primary" => "Outline Primary",
				"btn btn-outline-secondary" => "Outline Secondary",
				"btn btn-outline-tertiary" => "Outline Tertiary",
				"btn btn-outline-danger" => "Outline Danger",
				"btn btn-outline-warning" => "Outline Warning",
				"btn btn-outline-success" => "Outline Success",
				"btn btn-outline-info" => "Outline Info",
				"btn btn-outline-light" => "Outline Light",
			],
			"default_value" => "btn btn-primary",
			"allow_null" => 0,
			"multiple" => 0,
			"ui" => 0,
			"return_format" => "value",
			"ajax" => 0,
			"placeholder" => "",
		],
		[
			"key" => "field_398472hnfdb3e9123r3w5",
			"label" => "Component Link 5",
			"name" => "component_link_5",
			"type" => "link",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"return_format" => "array",
		],
		[
			"key" => "field_235rtserth53wgryt4r5",
			"label" => "Component Link Style 5",
			"name" => "component_link_style_5",
			"type" => "select",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_398472hnfdb3e9123r3w5",
						"value" => "!empty",
					],
				],
			],
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"btn btn-primary" => "Primary",
				"btn btn-secondary" => "Secondary",
				"btn btn-tertiary" => "Tertiary",
				"btn btn-danger" => "Danger",
				"btn btn-warning" => "Warning",
				"btn btn-success" => "Success",
				"btn btn-info" => "Info",
				"btn btn-light" => "Light",
				"btn btn-text" => "Text",
				"btn btn-link" => "Link",
				"btn btn-outline-primary" => "Outline Primary",
				"btn btn-outline-secondary" => "Outline Secondary",
				"btn btn-outline-tertiary" => "Outline Tertiary",
				"btn btn-outline-danger" => "Outline Danger",
				"btn btn-outline-warning" => "Outline Warning",
				"btn btn-outline-success" => "Outline Success",
				"btn btn-outline-info" => "Outline Info",
				"btn btn-outline-light" => "Outline Light",
			],
			"default_value" => "btn btn-primary",
			"allow_null" => 0,
			"multiple" => 0,
			"ui" => 0,
			"return_format" => "value",
			"ajax" => 0,
			"placeholder" => "",
		],
	];


	/**
	 * @var array An array of Advanced Custom Field data.
	 *
	 * @since 0.7.5
	 *
	 * phpcs:disable
	 */
	public $design_tab = [
		[
			"key" => "field_5fi3o49x4cbxn",
			"label" => "Design",
			"name" => "",
			"type" => "tab",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			"placement" => "top",
			"endpoint" => 0,
		],
		[
			"key" => "field_5e435yrtuhgf",
			"label" => "Padding Top",
			"name" => "component_padding_top",
			"type" => "number",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"allow_null" => 1,
			'default_value' => 100,
			'append' => 'px'
		],
		[
			"key" => "field_5e435yrtu345y",
			"label" => "Padding Bottom",
			"name" => "component_padding_bottom",
			"type" => "number",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"allow_null" => 1,
			'default_value' => 0,
			'append' => 'px'
		],
		[
			"key" => "field_5e43gh34h5n4rtu345y",
			"label" => "Text Align",
			"name" => "component_text_align",
			"type" => "select",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			'choices' => [
				'' => 'Default',
				'start' => 'Left',
				'center' => 'Center',
				'end' => 'Right',
			],
			'return_format' => 'value',
			'default_value' => ''
		],
		[
			"key" => "field_5g43gerfwrv345y",
			"label" => "Text Full Width",
			"name" => "component_text_width",
			"type" => "button_group",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			'choices' => [
				'' => 'No',
				'mw-100' => 'Yes',
			],
			'return_format' => 'value',
			'default_value' => ''
		],
		[
			"key" => "field_34923ioqwneadfaweae",
			"label" => "Block Template",
			"name" => "block_template",
			"type" => "select",
			"instructions" => "",
			"required" => 1,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			// choices populated dynamically
			"choices" => [],
			"default_value" => '',
			"allow_null" => 0,
			"multiple" => 0,
			"ui" => 0,
			"ajax" => 0,
			"return_format" => "value",
			"placeholder" => "",
		],
		[
			"key" => "field_5e60236843a77",
			"label" => "Color Theme",
			"name" => "component_color_theme",
			"type" => "button_group",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"light" => "Light",
				"dark" => "Dark",
			],
			"allow_null" => 0,
			"other_choice" => 0,
			"default_value" => "white",
			"layout" => "horizontal",
			"return_format" => "value",
			"save_other_choice" => 0,
		],
		[
			"key" => "field_5e602rvevvva77",
			"label" => "Cut container or background corners?",
			"name" => "component_cont_or_bg",
			"type" => "button_group",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"container" => "Container",
				"background" => "Background",
			],
			"allow_null" => 0,
			"other_choice" => 0,
			"default_value" => "container",
			"layout" => "horizontal",
			"return_format" => "value",
		],
		[
			"key" => "field_65je76ruymyn45y",
			"label" => "Top left corner",
			"name" => "component_tlc",
			"type" => "number",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			'default_value' => 0,
			'append' => 'px'
		],
		[
			"key" => "field_65je76ruymyn46y",
			"label" => "Top right corner",
			"name" => "component_trc",
			"type" => "number",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			'default_value' => 0,
			'append' => 'px'
		],
		[
			"key" => "field_65je76ruymyn47y",
			"label" => "Bottom left corner",
			"name" => "component_blc",
			"type" => "number",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			'default_value' => 0,
			'append' => 'px'
		],
		[
			"key" => "field_65je76ruymyn48y",
			"label" => "Bottom right corner",
			"name" => "component_brc",
			"type" => "number",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			'default_value' => 0,
			'append' => 'px'
		],
	];

	/**
	 * @var array An array of Advanced Custom Field data.
	 *
	 * @since 0.7.0
	 * @since 2.7.0 Background tab removed. ACF fields moved to design tab.
	 */
	public $background_tab = [
		[
			"key" => "field_5bdb3cc7d7d1b",
			"label" => "Background Type",
			"name" => "background_type",
			"type" => "button_group",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_4trydgsdfzses",
						"operator" => "!=",
						"value" => "video",
					],
				],
			],
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			"choices" => [
				"color" => "Color",
				"image" => "Image",
			],
			"allow_null" => 1,
			"default_value" => "color",
			"layout" => "horizontal",
			"return_format" => "value",
		],
		[
			"key" => "field_5bdb3cc7d7d49",
			"label" => "Background color 1",
			"name" => "background_color",
			"type" => "color_picker",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_5bdb3cc7d7d1b",
						"operator" => "==",
						"value" => "color",
					],
				],
			],
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
		],
		[
			"key" => "field_5bdb3cc7d7sdfsfd49",
			"label" => "Background color 2",
			"name" => "background_color_2",
			"type" => "color_picker",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_5bdb3cc7d7d1b",
						"operator" => "==",
						"value" => "color",
					],
				],
			],
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
		],
		[
			"key" => "field_5bdb3cc7d7dcc",
			"label" => "Image",
			"name" => "background_image",
			"type" => "image",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => [
				[
					[
						"field" => "field_5bdb3cc7d7d1b",
						"operator" => "==",
						"value" => "image",
					],
					[
						"field" => "field_5d38800ecd388",
						"operator" => "!=",
						"value" => 1,
					],
				],
			],
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"return_format" => "array",
			"preview_size" => "medium",
			"library" => "all",
			"min_width" => "",
			"min_height" => "",
			"min_size" => "",
			"max_width" => "",
			"max_height" => "",
			"max_size" => "",
			"mime_types" => "",
		],
		[
			"key" => "field_5bd23sdfgh43fr49",
			"label" => "Container color 1",
			"name" => "container_color_1",
			"type" => "color_picker",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
		],
		[
			"key" => "field_5bd2343tgrer49",
			"label" => "Container color 2",
			"name" => "container_color_2",
			"type" => "color_picker",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
		],
	];

	/**
	 * @var array An array of Advanced Custom Field data.
	 *
	 * @since 2.4.0
	 */
	public $settings_tab = [
		[
			"key" => "field_5903enawe09eh",
			"label" => "Settings",
			"name" => "",
			"type" => "tab",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "",
				"class" => "",
				"id" => "",
			],
			"placement" => "top",
			"endpoint" => 0,
		],
		[
			"key" => "field_44tsertya3439",
			"label" => "Component ID",
			"name" => "component_id",
			"type" => "text",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
			"placeholder" => "",
			"prepend" => "",
			"append" => "",
			"maxlength" => "",
		],
		[
			"key" => "field_44tfasdghte567",
			"label" => "Component Class",
			"name" => "component_class",
			"type" => "text",
			"instructions" => "",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"default_value" => "",
			"placeholder" => "",
			"prepend" => "",
			"append" => "",
			"maxlength" => "",
		],
		[
			"key" => "field_636ec723f6c1a",
			"label" => "Block Visibility",
			"name" => "block_visibility",
			"aria-label" => "",
			"type" => "button_group",
			"instructions" => "Hide the block on the frontend",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"capability" => "",
			"choices" => [
				"visible" => "Visible",
				"hidden" => "Hidden",
			],
			"default_value" => "visible",
			"return_format" => "value",
			"allow_null" => 0,
			"other_choice" => 0,
			"layout" => "horizontal",
			"save_other_choice" => 0,
		],
		[
			"key" => "field_636ec_block_in_modal",
			"label" => "Block In Modal",
			"name" => "block_in_modal",
			"aria-label" => "",
			"type" => "button_group",
			"instructions" => "Show component in a modal?",
			"required" => 0,
			"conditional_logic" => 0,
			"wrapper" => [
				"width" => "50",
				"class" => "",
				"id" => "",
			],
			"capability" => "",
			"choices" => [
				false => "No",
				true => "Yes",
			],
			"default_value" => false,
			"return_format" => "value",
			"allow_null" => 0,
			"other_choice" => 0,
			"layout" => "horizontal",
			"save_other_choice" => 0,
		],
	];
}
