<?php

return array(
	'key' => 'group_blurb',
	'title' => 'Blurbs',
	'fields' => array(
		array(
			'key' => 'field_5c4219ab9a521',
			'label' => 'Blurbs',
			'name' => 'blurbs',
			'type' => 'repeater',
			'instructions' => 'Collection of Blurbs',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c4219499a51e',
			'min' => 0,
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Blurb',
			'sub_fields' => array(
				array(
					'key' => 'field_5c42190d9a51d',
					'label' => 'Image Icon',
					'name' => 'blurb_image_icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
				),
				array(
					'key' => 'field_5c4219499a51e',
					'label' => 'Title',
					'name' => 'blurb_title',
					'type' => 'textarea',
					'instructions' => 'Blurb Title',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '65',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_5c4219629a51f',
					'label' => 'Content',
					'name' => 'blurb_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_5c4219799a520',
					'label' => 'Button',
					'name' => 'blurb_button',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
	),
);
