<?php

return array(
	'key' => 'group_5b73a6c29e165',
	'title' => 'Hero',
	'fields' => array(
		array(
			'key' => 'field_5c23465eythtgf',
			'label' => 'Content align',
			'name' => 'hero_content_align',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'start' => 'Left',
				'center' => 'Center',
				'end' => 'Right',
			),
			'default_value' => 'start',
		),
		array(
			'key' => 'field_5c234rtegfdbd23',
			'label' => 'Image',
			'name' => 'hero_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
		),
		array(
			'key' => 'field_5c2346ht435tggf',
			'label' => 'Image position',
			'name' => 'hero_image_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'right' => 'Image Right',
				'left' => 'Image Left',
			),
			'default_value' => 'right',
		),
		array(
			'key' => 'field_523r4grterbdf',
			'label' => 'Small images',
			'name' => 'hero_small_images',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 3,
			'layout' => 'row',
			'button_label' => 'Add Image',
			'sub_fields' => array(
				array(
					'key' => 'field_5c234rgetd24ger',
					'label' => 'Image',
					'name' => 'hero_small_images_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
				),
			),
		),
	),
	'background_tab' => array(
		array(
			'key' => 'field_5bbbc98109983',
			'label' => 'Poster',
			'name' => 'background_video_poster',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_4trydgsdfzses',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
		),
		array(
			'key' => 'field_5bbbae7d99ebb',
			'label' => 'Video Desktop mp4',
			'name' => 'background_video_desktop_mp4',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_4trydgsdfzses',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.mp4',
		),
		array(
			'key' => 'field_5bbbaedb99ebe',
			'label' => 'Video Desktop webm',
			'name' => 'background_video_desktop_webm',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_4trydgsdfzses',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.webm',
		),
		array(
			'key' => 'field_5bbbaea799ebc',
			'label' => 'Video Mobile mp4',
			'name' => 'background_video_mobile_mp4',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_4trydgsdfzses',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.mp4',
		),
		array(
			'key' => 'field_5bbbaeb999ebd',
			'label' => 'Video Mobile webm',
			'name' => 'background_video_mobile_webm',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_4trydgsdfzses',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.webm',
		),
		array(
			'key' => 'field_5d388bada9d86',
			'label' => 'Background Video Properties',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_4trydgsdfzses',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enter the Background video properties below',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5d388c09a9d88',
			'label' => 'Background Video Muted',
			'name' => 'background_video_muted',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_4trydgsdfzses',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Audio Muted',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d388c4da9d8a',
			'label' => 'Background Video Loop',
			'name' => 'background_video_loop',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_4trydgsdfzses',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Loop Video',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'design_tab' => array(
		array(
			'key' => 'field_4trydgsdfzses',
			'label' => 'Background Video',
			'name' => 'background_video',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'other' => 'Other',
				'video' => 'Video',
			),
			'allow_null' => 1,
			'default_value' => 'other',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
);
