<?php

return array(
	'key' => 'group_slider_text',
	'title' => 'Slider Text',
	'fields' => array(
		array(
			'key' => 'field_55436yrthgsdf41',
			'label' => 'Slides',
			'name' => 'slides',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array(
				array(
					'key' => 'field_5bbd23449e042',
					'label' => 'Slide Header',
					'name' => 'slide_header',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_5f8m8a5skdbc2',
					'label' => 'Header Tag',
					'name' => 'slide_header_tag',
					'type' => 'button_group',
					'instructions' => 'Choose a component Header Tag',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5bbd23449e042',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'h1' => 'H1',
						'h2' => 'H2',
						'h3' => 'H3',
						'h4' => 'H4',
						'h5' => 'H5',
						'h6' => 'H6',
						'p' => 'P',
					),
					'allow_null' => 0,
					'default_value' => 'h2',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5bbd23b19e044',
					'label' => 'Slide Content',
					'name' => 'slide_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_5bd2365cd45cc',
					'label' => 'Button',
					'name' => 'slide_button',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '51',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				array(
					'key' => 'field_5bsbsgehtrtgbfd040',
					'label' => 'Slide Icon',
					'name' => 'slide_icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5bsb5g35hgsgsdgsdg',
					'label' => 'Slide Icon Font Awesome',
					'name' => 'slide_icon_fa',
					'type' => 'text',
					'instructions' => 'Go to: <a href="https://fontawesome.com/icons" target="_blank">Font Awesome</a>, choose an icon and copy the code here.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
			),
		),
	),
);
