<?php

return array(
	'key' => 'group_tabs',
	'title' => 'Tabs',
	'fields' => array(
		array(
			'key' => 'field_5bcdf0732b2f9',
			'label' => 'Tabs',
			'name' => 'tabs',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Tab/Panel',
			'sub_fields' => array(
				array(
					'key' => 'field_5bcdf3b40791b',
					'label' => 'Tab',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5bcdf08d2b2fb',
					'label' => 'Tab Label',
					'name' => 'tab_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bcdf3c40791c',
					'label' => 'Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5bcbobu82b2fa',
					'label' => 'Panel Title',
					'name' => 'panel_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					"key" => "field_5bcbobu82b2fa_tag",
					"label" => "Panel Title Tag",
					"name" => "panel_title_tag",
					"type" => "button_group",
					"instructions" => "Choose Panel Title Tag",
					"required" => 0,
					"conditional_logic" => [
						[
							[
								"field" => "field_5bcbobu82b2fa",
								"operator" => "!=empty",
							],
						],
					],
					"wrapper" => [
						"width" => "33.333",
						"class" => "",
						"id" => "",
					],
					"choices" => [
						"h1" => "H1",
						"h2" => "H2",
						"h3" => "H3",
						"h4" => "H4",
						"h5" => "H5",
						"h6" => "H6",
						"p" => "P",
					],
					"allow_null" => 0,
					"default_value" => "h3",
					"layout" => "horizontal",
					"return_format" => "value",
				),
				array(
					"key" => "field_5bcbobu82b2fa_style",
					"label" => "Panel Title Style",
					"name" => "panel_title_style",
					"type" => "select",
					"instructions" => "Choose Panel Title Style (optional).",
					"required" => 0,
					"conditional_logic" => [
						[
							[
								"field" => "field_5bcbobu82b2fa",
								"operator" => "!=empty",
							],
						],
					],
					"wrapper" => [
						"width" => "33.333",
						"class" => "",
						"id" => "",
					],
					"choices" => [
						"h1" => "H1",
						"h2" => "H2",
						"h3" => "H3",
						"h4" => "H4",
						"h5" => "H5",
						"h6" => "H6",
						"lead" => "Lead",
					],
					"default_value" => [
						0 => "default",
					],
					"allow_null" => 1,
					"multiple" => 0,
					"ui" => 0,
					"ajax" => 0,
					"return_format" => "value",
					"placeholder" => "",
				),
				array(
					"key" => "field_5bcbobu82b2fa_class",
					"label" => "Panel Title Class",
					"name" => "panel_title_class",
					"type" => "text",
					"instructions" => "Input Panel Title Class (optional).",
					"required" => 0,
					"conditional_logic" => [
						[
							[
								"field" => "field_5bcbobu82b2fa",
								"operator" => "!=empty",
							],
						],
					],
					"wrapper" => [
						"width" => "33.333",
						"class" => "",
						"id" => "",
					],
					"allow_null" => 1,
					"placeholder" => "",
				),
				array(
					'key' => 'field_5bcdf0db2de34',
					'label' => 'Panel Content',
					'name' => 'panel_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5bdassdnbkjgkcc4',
					'label' => 'Panel Image',
					'name' => 'panel_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5bdassdnbkjgkcc4_position',
					'label' => 'Panel Image position',
					'name' => 'panel_image_position',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'right' => 'Image Right',
						'left' => 'Image Left',
					),
					'default_value' => 'left',
				),
				array(
					'key' => 'field_5bcdf0e92de35',
					'label' => 'Panel Link',
					'name' => 'panel_link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				array(
					"key" => "field_5bcdf0e92de35_style",
					"label" => "Panel Link Style",
					"name" => "panel_link_style",
					"type" => "select",
					"instructions" => "",
					"required" => 0,
					"conditional_logic" => [
						[
							[
								"field" => "field_5bcdf0e92de35",
								"value" => "!empty",
							],
						],
					],
					"wrapper" => [
						"width" => "",
						"class" => "",
						"id" => "",
					],
					"choices" => [
						"btn btn-primary" => "Primary",
						"btn btn-secondary" => "Secondary",
						"btn btn-tertiary" => "Tertiary",
						"btn btn-danger" => "Danger",
						"btn btn-warning" => "Warning",
						"btn btn-success" => "Success",
						"btn btn-info" => "Info",
						"btn btn-light" => "Light",
						"btn btn-text" => "Text",
						"btn btn-link" => "Link",
						"btn btn-outline-primary" => "Outline Primary",
						"btn btn-outline-secondary" => "Outline Secondary",
						"btn btn-outline-tertiary" => "Outline Tertiary",
						"btn btn-outline-danger" => "Outline Danger",
						"btn btn-outline-warning" => "Outline Warning",
						"btn btn-outline-success" => "Outline Success",
						"btn btn-outline-info" => "Outline Info",
						"btn btn-outline-light" => "Outline Light",
					],
					"default_value" => "btn btn-primary",
					"allow_null" => 0,
					"multiple" => 0,
					"ui" => 0,
					"return_format" => "value",
					"ajax" => 0,
					"placeholder" => "",
				),
			),
		),
	),
);
