<?php

return array(
	'key' => 'group_5bce6c5b9e6ee',
	'title' => 'Counters',
	'fields' => array(
		array(
			'key' => 'field_5bce6c6b4714a',
			'label' => 'Counter',
			'name' => 'counters',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5bce6c934714c',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Counter',
			'sub_fields' => array(
				array(
					'key' => 'field_12524952945',
					'label' => 'Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5bce6ca24714e',
					'label' => 'Counter Prefix',
					'name' => 'counter_prefix',
					'type' => 'text',
					'instructions' => 'Character shown before the number',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Prefix',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bce6c774714b',
					'label' => 'Final Number',
					'name' => 'counter_number',
					'type' => 'number',
					'instructions' => 'Number to count up to',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Final Number',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5bce6cf04714f',
					'label' => 'Counter Suffix',
					'name' => 'counter_suffix',
					'type' => 'text',
					'instructions' => 'Character shown after the number',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Suffix',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c42sdf0d9a51d',
					'label' => 'Counter Image',
					'name' => 'counter_image',
					'type' => 'image',
					'instructions' => 'Image graphic that is positioned above the title.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
				),
				array(
					'key' => 'field_5bce6c934714c',
					'label' => 'Title',
					'name' => 'counter_title',
					'type' => 'text',
					'instructions' => 'Main title below the number',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_3948c5nu02xrn',
					'label' => 'Options',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5x3439sdj4x48',
					'label' => 'Starting Value',
					'name' => 'counter_start_val',
					'type' => 'number',
					'instructions' => 'The number to start counting from. (Default 0).',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Starting Number',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5cdef2125033a',
					'label' => 'Use Easing',
					'name' => 'counter_use_easing',
					'type' => 'true_false',
					'instructions' => 'Ease Animation',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fsrcn9850xm',
					'label' => 'Counter Duration',
					'name' => 'counter_duration',
					'type' => 'number',
					'instructions' => 'How long to take to count from the starting number to the final number (in seconds).',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '2',
					'prepend' => '',
					'append' => 'seconds',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5cdef2415033b',
					'label' => 'Use Grouping',
					'name' => 'counter_use_grouping',
					'type' => 'true_false',
					'instructions' => 'Example: 1,000 vs 1000',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5cdef2505033c',
					'label' => 'Separator',
					'name' => 'counter_separator',
					'type' => 'text',
					'instructions' => 'Grouping Separator (\',\')',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Separator',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5cdef2a05033d',
					'label' => 'Decimal',
					'name' => 'counter_decimal',
					'type' => 'text',
					'instructions' => 'Decimal (\'.\')',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Decimal',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5cdef2dc5033e',
					'label' => 'Decimal Places',
					'name' => 'counter_decimal_places',
					'type' => 'number',
					'instructions' => 'Number of Decimal Places',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 0,
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => 1,
				),
			),
		),
	),
);
