<?php

return array(
	'key' => 'group_5b74333ef40a0',
	'title' => 'Cards',
	'fields' => array(
		array(
			'key' => 'field_5b7433hqhrbefdrvdv91',
			'label' => 'Cards Image',
			'name' => 'cards_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b7433524tg3rvdv91',
			'label' => 'Cards Background Color',
			'name' => 'cards_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b7424g3rvdv91',
			'label' => 'Cards Shadow',
			'name' => 'cards_shadow',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				null => 'Default',
				'shadow-none' => 'None',
				'shadow-sm' => 'Small',
				'shadow' => 'Medium',
				'shadow-lg' => 'Large',
			),
			'default_value' => null,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6334d3792146f',
			'label' => 'Card Image Style',
			'name' => 'card_image_style',
			'type' => 'radio',
			'instructions' => 'Choose the image style / position for this cards component',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'capability' => '',
			'choices' => array(
				'background' => 'Background',
				'top' => 'Image Top',
				'icon-top' => 'Icon Top',
				'numbers' => 'Numbered',
				'small' => 'Small Image Testimonial',
				'small-big' => 'Big Image Testimonial'
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'top',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6334d2r2g3btsdff',
			'label' => 'Custom Columns Count',
			'name' => 'card_custom_columns',
			'type' => 'radio',
			'instructions' => 'Choose if you want to use custom columns count for this cards component',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'capability' => '',
			'choices' => array(
				0 => 'No',
				1 => 'Yes'
			),
			'ui' => 1,
			'default_value' => 0,
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_1f3j_cards_col_xs',
			'label' => 'Columns XS',
			'name' => 'cards_cols_xs',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'field' => 'field_6334d2r2g3btsdff',
					'operator' => '==',
					'value' => '1',
				)
			),
			'wrapper' => array(
				'width' => '16.6666',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				1   => '1',
				2   => '2',
				3	=> '3',
				4	=> '4',
				6 	=> '6',
				12 	=> '12',
			),
			'default_value' => get_field('cards_cols_xs', "options") ? get_field('cards_cols_xs', "options") : 1,
			'placeholder' => '',
		),
		array(
			'key' => 'field_1f3j_cards_col_sm',
			'label' => 'Columns SM',
			'name' => 'cards_cols_sm',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'field' => 'field_6334d2r2g3btsdff',
					'operator' => '==',
					'value' => '1',
				)
			),
			'wrapper' => array(
				'width' => '16.6666',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				1   => '1',
				2   => '2',
				3	=> '3',
				4	=> '4',
				6 	=> '6',
				12 	=> '12',
			),
			'default_value' => get_field('cards_cols_xs', "options") ? get_field('cards_cols_xs', "options") : 1,
			'placeholder' => '',
		),
		array(
			'key' => 'field_1f3j_cards_col_md',
			'label' => 'Columns MD',
			'name' => 'cards_cols_md',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'field' => 'field_6334d2r2g3btsdff',
					'operator' => '==',
					'value' => '1',
				)
			),
			'wrapper' => array(
				'width' => '16.6666',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				1   => '1',
				2   => '2',
				3	=> '3',
				4	=> '4',
				6 	=> '6',
				12 	=> '12',
			),
			'default_value' => get_field('cards_cols_md', "options") ? get_field('cards_cols_md', "options") : 2,
			'placeholder' => '',
		),
		array(
			'key' => 'field_1f3j_cards_col_lg',
			'label' => 'Columns LG',
			'name' => 'cards_cols_lg',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'field' => 'field_6334d2r2g3btsdff',
					'operator' => '==',
					'value' => '1',
				)
			),
			'wrapper' => array(
				'width' => '16.6666',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				1   => '1',
				2   => '2',
				3	=> '3',
				4	=> '4',
				6 	=> '6',
				12 	=> '12',
			),
			'default_value' => get_field('cards_cols_lg', "options") ? get_field('cards_cols_lg', "options") : 2,
			'placeholder' => '',
		),
		array(
			'key' => 'field_1f3j_cards_col_xl',
			'label' => 'Columns XL',
			'name' => 'cards_cols_xl',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'field' => 'field_6334d2r2g3btsdff',
					'operator' => '==',
					'value' => '1',
				)
			),
			'wrapper' => array(
				'width' => '16.6666',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				1   => '1',
				2   => '2',
				3	=> '3',
				4	=> '4',
				6 	=> '6',
				12 	=> '12',
			),
			'default_value' => get_field('cards_cols_xl', "options") ? get_field('cards_cols_xl', "options") : 3,
			'placeholder' => '',
		),
		array(
			'key' => 'field_1f3j_cards_col_xxl',
			'label' => 'Columns XXL',
			'name' => 'cards_cols_xxl',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'field' => 'field_6334d2r2g3btsdff',
					'operator' => '==',
					'value' => '1',
				)
			),
			'wrapper' => array(
				'width' => '16.6666',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				1   => '1',
				2   => '2',
				3	=> '3',
				4	=> '4',
				6 	=> '6',
				12 	=> '12',
			),
			'default_value' => get_field('cards_cols_xxl', "options") ? get_field('cards_cols_xxl', "options") : 3,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b74334196d8f',
			'label' => 'Cards',
			'name' => 'cards',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5b74335696d91',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Card',
			'sub_fields' => array(
				array(
					'key' => 'field_5409m45n2ku6nsb',
					'label' => 'Sub Header',
					'name' => 'card_sub_header',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5b74335696d91',
					'label' => 'Header',
					'name' => 'card_header',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bbd2089youhb',
					'label' => 'Card Image',
					'name' => 'card_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							"field" => "field_6334d3792146f",
							"operator" => "!=",
							"value" => 'icon-top'
						),
						array(
							"field" => "field_6334d3792146f",
							"operator" => "!=",
							"value" => 'numbers'
						),
					),
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5bdfgsfdg3t5htrgsdbf',
					'label' => 'Card Stars',
					'name' => 'card_stars',
					'type' => 'number',
					'min' => 1,
					'max' => 5,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								"field" => "field_6334d3792146f",
								"operator" => "==",
								"value" => 'small'
							),
						),
						array(
							array(
								"field" => "field_6334d3792146f",
								"operator" => "==",
								"value" => 'small-big'
							),
						)
					),
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
				),
				array(
					'key' => 'field_5bb43t5htrgsdbf',
					'label' => 'Card Icon',
					'name' => 'card_icon',
					'type' => 'text',
					'instructions' => 'Find the icon on <a href="https://fontawesome.com/search" target="_blank">FontAwesome</a> website and copy it’s code here.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							"field" => "field_6334d3792146f",
							"operator" => "==",
							"value" => 'icon-top'
						),

					),
					'wrapper' => array(
						'width' => '33.3333',
						'class' => '',
						'id' => '',
					),
					'ui' => 1,
					'ajax' => 1,
					'allow_null' => 0,
				),
				array(
					'key' => 'field_5bsdfsdffdfe3gsdbf',
					'label' => 'Icon color',
					'name' => 'card_icon_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							"field" => "field_5bb43t5htrgsdbf",
							"operator" => "!=empty",
						),

					),
					'wrapper' => array(
						'width' => '33.3333',
						'class' => '',
						'id' => '',
					),
				),
				array(
					'key' => 'field_5g4rbefsfgggf',
					'label' => 'Icon size',
					'name' => 'card_icon_size',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							"field" => "field_5bb43t5htrgsdbf",
							"operator" => "!=empty",
						),

					),
					'wrapper' => array(
						'width' => '33.3333',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'value',
					'choices' => array(
						'fa-2xs' => '0.625x',
						'fa-xs' => '0.75x',
						'fa-sm' => '0.875x',
						'fa-1x' => '1x',
						'fa-2x' => '2x',
						'fa-3x' => '3x',
						'fa-4x' => '4x',
						'fa-5x' => '5x',
						'fa-6x' => '6x',
						'fa-7x' => '7x',
						'fa-8x' => '8x',
						'fa-9x' => '9x',
						'fa-10x' => '10x',
					),
					'default_value' => 'fa-1x',
				),
				array(
					'key' => 'field_5b74335b96d92',
					'label' => 'Content',
					'name' => 'card_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5cdc8980aa132',
					'label' => 'Card Link',
					'name' => 'card_link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
	),
);
