<?php

return array(
	'key' => 'group_text_media',
	'title' => 'Text Media',
	'fields' => array(
		array(
			'key' => 'field_5c2e677cafd9a',
			'label' => 'Media Type',
			'name' => 'text_media_media_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'image' => 'Image',
				'video' => 'Video',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5c2e6803afd9b',
			'label' => 'Image',
			'name' => 'text_media_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.jpg, .jpeg, .webp, .svg, .png, .gif',
		),
		array(
			'key' => 'field_32f44gb3vewrfdff',
			'label' => 'Image aspect ratio',
			'name' => 'text_media_image_aspect_ratio',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				null => 'Default',
				'1x1' => '1x1',
				'4x3' => '4x3',
				'16x9' => '16x9',
				'21x9' => '21x9',
				'4x5' => '4x5',
			),
			'return_format' => 'value',
			'default_value' => null,
		),
		array(
			'key' => 'field_5c2e67aa7cafd9a',
			'label' => 'Video Behavior',
			'name' => 'video_behavior',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'modal' => 'Modal',
				'inline' => 'Inline',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_333r24t3y5htebfdq4ew',
			'label' => 'Autoplay',
			'name' => 'video_autoplay',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				true => 'Yes',
				false => 'No',
			),
			'default_value' => false,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_890fh2q33q4awew',
			'label' => 'Video Source',
			'name' => 'source',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'media-library' => 'Media Library',
				'embed' => 'Embed',
			),
			'default_value' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c2e686eafd9d',
			'label' => 'Poster',
			'name' => 'text_media_video_poster',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.jpg, .jpeg, .png, .mp4, .webm, .webp, .svg, .gif',
		),
		array(
			'key' => 'field_5c2e6828afd9c',
			'label' => 'Video',
			'name' => 'text_media_video',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_890fh2q33q4awew',
						'operator' => '==',
						'value' => 'media-library',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.mp4, .webm',
		),
		array(
			'key' => 'field_631f8cfabaa107',
			'label' => 'Embed URL',
			'name' => 'embed',
			'type' => 'text',
			'instructions' => '',
			'placeholder' => 'Enter URL',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_890fh2q33q4awew',
						'operator' => '==',
						'value' => 'embed',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'capability' => '',
			'width' => '',
			'height' => '',
		),
	),
);
